name: Deploy to Amazon ECS

on:
  workflow_dispatch: # allows manual trigger
  push:
    branches:
      - master
    tags:
      - "v*"

jobs:
  deploy:
    name: Deploy to ECS
    runs-on: ubuntu-latest
    environment: deploy-env
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t notification-app .
          docker tag notification-app:latest 436471025548.dkr.ecr.eu-north-1.amazonaws.com/notification-app
          docker push 436471025548.dkr.ecr.eu-north-1.amazonaws.com/notification-app

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task-def.json
          service: notification-service
          cluster: notification-cluster
          wait-for-service-stability: true
